# Generated by Django 3.0.3 on 2020-03-23 21:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('description', models.TextField(default='No Description Available')),
            ],
        ),
        migrations.CreateModel(
            name='LesionScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=256)),
                ('score', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='LesionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(default='No Description Available')),
            ],
        ),
        migrations.CreateModel(
            name='LesionReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(unique=True, upload_to='')),
                ('lesion_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='training.LesionType')),
            ],
        ),
        migrations.CreateModel(
            name='LesionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(unique=True, upload_to='')),
                ('healing_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='training.HealingType')),
                ('lesion_types', models.ManyToManyField(to='training.LesionType')),
            ],
        ),
        migrations.CreateModel(
            name='HealingReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(unique=True, upload_to='')),
                ('healing_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='training.HealingType')),
            ],
        ),
    ]
