# Generated by Django 2.1.5 on 2019-10-15 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='score',
            new_name='lesion_type',
        ),
    ]
