# Generated by Django 3.0.3 on 2020-03-27 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_healingscore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healingscore',
            old_name='iamge_url',
            new_name='image_url',
        ),
    ]
