# Generated by Django 2.1.5 on 2019-10-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_auto_20191015_0516'),
    ]

    operations = [
        migrations.CreateModel(
            name='LesionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesion_type', models.IntegerField()),
                ('imageUrl', models.ImageField(unique=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
