# Generated by Django 3.0.3 on 2020-03-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_auto_20200327_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healingscore',
            name='score',
            field=models.CharField(max_length=1),
        ),
    ]
