# Generated by Django 2.1.5 on 2019-10-15 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_auto_20191015_0729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesionimage',
            old_name='imageUrl',
            new_name='image_url',
        ),
    ]
