# Generated by Django 3.0.3 on 2020-07-01 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_auto_20200422_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesionimage',
            name='age',
            field=models.CharField(default='None provided', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesionimage',
            name='sex',
            field=models.CharField(default='None provided', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesionimage',
            name='site',
            field=models.CharField(default='None provided', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesionimage',
            name='time_period',
            field=models.CharField(default='None provided', max_length=256),
            preserve_default=False,
        ),
    ]
