# Generated by Django 2.1.5 on 2019-11-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_lesionimage_reference_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LesionReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesion_type', models.CharField(max_length=256)),
                ('image_url', models.ImageField(unique=True, upload_to='')),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='lesionimage',
            name='reference_image',
        ),
    ]
