# Generated by Django 3.0.3 on 2020-08-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_auto_20200701_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='healingscore',
            name='education_level',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesionscore',
            name='education_level',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
    ]
