# Generated by Django 3.0.2 on 2020-01-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_auto_20191121_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealingReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('healing_type', models.CharField(max_length=256)),
                ('image_url', models.ImageField(unique=True, upload_to='')),
            ],
        ),
    ]
