# Generated by Django 3.0.3 on 2020-08-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_auto_20200824_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='healingscore',
            name='times_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lesionscore',
            name='times_taken',
            field=models.IntegerField(default=0),
        ),
    ]
