# Generated by Django 3.0.3 on 2020-08-25 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_auto_20200824_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healingscore',
            name='times_taken',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='lesionscore',
            name='times_taken',
            field=models.CharField(max_length=256),
        ),
    ]
