# Generated by Django 3.0.2 on 2020-01-15 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_auto_20200109_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesionreference',
            name='description',
        ),
        migrations.AddField(
            model_name='lesionreference',
            name='lesion_description',
            field=models.TextField(default='No Description Available'),
        ),
        migrations.AddField(
            model_name='lesiontype',
            name='lesion_description',
            field=models.TextField(default='No Description Available'),
        ),
        migrations.RemoveField(
            model_name='lesionreference',
            name='lesion_type',
        ),
        migrations.AddField(
            model_name='lesionreference',
            name='lesion_type',
            field=models.ManyToManyField(to='training.LesionType'),
        ),
    ]
