# Generated by Django 3.0.2 on 2020-01-15 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_auto_20200115_0448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesionreference',
            name='lesion_description',
        ),
    ]
