# Generated by Django 3.0.2 on 2020-01-15 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_auto_20200115_0555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesionreference',
            name='lesion_type',
        ),
        migrations.AddField(
            model_name='lesionreference',
            name='lesion_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='training.LesionType'),
        ),
    ]
