# Generated by Django 3.0.2 on 2020-01-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0014_auto_20200115_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesionimage',
            name='lesion_types',
            field=models.ManyToManyField(blank=True, related_name='lesion_images', to='training.LesionType'),
        ),
    ]
