# Generated by Django 3.0.2 on 2020-01-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0017_auto_20200115_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesionimage',
            name='lesion_types',
            field=models.ManyToManyField(to='training.LesionType'),
        ),
    ]
