# Generated by Django 3.0.2 on 2020-01-15 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0018_auto_20200115_0807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesiontype',
            old_name='lesion_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='lesiontype',
            old_name='lesion_type',
            new_name='name',
        ),
    ]
