# Generated by Django 3.0.2 on 2020-01-17 23:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0019_auto_20200115_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healingreference',
            name='healing_type',
        ),
        migrations.AddField(
            model_name='healingreference',
            name='degree',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
