# Generated by Django 3.0.2 on 2020-01-18 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0020_auto_20200117_2357'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HealingReference',
        ),
    ]
