# Generated by Django 3.0.2 on 2020-01-18 00:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0021_delete_healingreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealingReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('image_url', models.ImageField(unique=True, upload_to='')),
            ],
        ),
    ]
