# Generated by Django 3.0.2 on 2020-01-18 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0022_healingreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='healingreference',
            name='description',
            field=models.TextField(default='No Description Available'),
        ),
    ]
