# Generated by Django 3.0.2 on 2020-02-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0023_healingreference_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='LesionScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.ManyToManyField(to='training.LesionType')),
            ],
        ),
    ]
