# Generated by Django 3.0.2 on 2020-02-19 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0024_lesionscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesionscore',
            name='image_url',
            field=models.ImageField(default=None, unique=True, upload_to=''),
            preserve_default=False,
        ),
    ]
