# Generated by Django 3.0.2 on 2020-02-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0025_lesionscore_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesionscore',
            name='image_url',
            field=models.CharField(max_length=256),
        ),
    ]
