# Generated by Django 3.0.2 on 2020-02-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0026_auto_20200219_0521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesionscore',
            name='scores',
        ),
        migrations.AddField(
            model_name='lesionscore',
            name='scores',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
