# Generated by Django 3.0.2 on 2020-02-19 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0027_auto_20200219_0605'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LesionScore',
        ),
    ]
