# Generated by Django 3.0.2 on 2020-02-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0028_delete_lesionscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='LesionScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=256)),
                ('scores', models.CharField(max_length=256)),
            ],
        ),
    ]
