# Generated by Django 3.0.2 on 2020-02-19 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0029_lesionscore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesionscore',
            old_name='scores',
            new_name='score',
        ),
    ]
